server:
  port: 8080

spring:
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    datasource:
      url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE"
      username: sa
      password: sa
      driverClassName: org.h2.Driver