server:
  port: 9000

params:
  datasource:
    jdbcUrl: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password: sa
    driverClassName: org.h2.Driver

spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

logging.level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE